# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTdR1PlaO9cTx-AbirE-joJuAjrL-gmG

**Different Data Types in Python**

**LIST**
"""

list1= [1,2,True,3.5,"Michale"]
print(list1)

list2= ["Mohan",False,3,5]
list3= list1 + list2
print(list3)

list3= list1 + list2
print(list3)

list1[1]=3
print(list1)

list1.append(100)
print(list1)

del list1
print(list1)

"""**Tuple**"""

my_tuple = (1, 2, 3, 'four', 5.0, True)
print(my_tuple)

my_tuple[2]= 4
print(my_tuple)

my_tuple.insert(2,100)
print(my_tuple)

my_tuple1 = (999,1000,"SMK")
my_tuple2 =my_tuple + my_tuple1
print(my_tuple2)

my_tuple1.append(56)
print(my_tuple1)

"""**Dictionary**"""

my_dic ={
    "Username" : "Hellomohan",
    "Laptop" : "HP",
    "Password" : 123456789,
    "Model" : "Elitebook"
}
print(my_dic)

my_dic["Username"]="Hellomohan0504"
print(my_dic)

my_dic["YOM"] = 2023
print(my_dic)

"""**Set**"""

set1 = {2,54,64,20,100,3}
print(set1)

set1.add(29)
print(set1)

set2={"Mohan",True,44,45,2}
set3=set1.union(set2)
print(set3)

set4 = set1&set2
print(set4)

