# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rx7lVLqWTOAWgf7Z4YcVvjNcruMCaKrv

**Simple calculator using python**
"""

while True:
  print("Enter x to exit or quit.")
  num1 = input("Enter the value: ")
  if num1 == "x":
    break
  num2 = input("Enter the value: ")
  if num2 == "x":
    break 
  num1 = float(num1)
  num2 = float(num2)

  print("Enter the operation you want to perform")
  print("+ for addition")
  print("- for subtraction")
  print("* for multiplication")
  print("/ for division")  

  choice = input("Enter choice: ")

  if choice == "+":
    result=num1+num2
  elif choice == "-":
    result=num1-num2
  elif choice == "*":
    result=num1*num2
  elif choice == "/":
    result=num1/num2
  else:
    print("Invalid Choice")
    continue
  print("Result = ", result)

filename = "Simple_calculator.txt"
with open(filename, "w") as f:
    f.write(str(result))
print("Output stored in file: ", filename)